# ===========================================
# Information Settings
# ===========================================

#navigation
menu: 
  Archives: archives/
  About: about/
  Programming: categories/programming/
  Supercomputer: categories/supercomputer/
  Manufacture: categories/manufacture/
  News: categories/news/
  ROFY: categories/recommended-of-the-year/
  # RSS: /atom.xml

# favicon
favicon: /images/favicon.png

# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Mobile-Header
# light | dark
mobile-header: dark

# Scheme
# banderole | balance
scheme: banderole

## Banderole
# Header Style
# line | block
header-style: block

# Article Header Sign
header_sign: ∮

# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: purple

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  # license: 

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    # wechat:
    # paypal:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments: 
  enable: true

  # disqus: 
  # livere_datauid:

  # changyan:
  #   appid: 
  #   appkey: 

  # gitment:
  #   owner:
  #   repo:
  #   client_id:
  #   client_secret:

# sub //Please just fill out ID.
sub:
  facebook: 1
  twitter: 2
  instagram: 3
  weibo: 4
  zhihu: 5
  github: 6
  linkedin: 7
  douban: 8

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google:
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: false

# ===========================================
# Theme Settings
# ===========================================

# mathjax
mathjax: false

# lightbox
lightbox: true

# lazyload
lazyload: false

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2010

# plugin
# plugins:

# about
# self:  

# ===========================================
# Search Settings
# ===========================================

# Search 
search:
  enable: true
  label: Give me the keyword

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: Hel

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 2.4

#theme_author: Co1MugX
